// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: KNArchives_sos.proto

package kpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpecSetTransitionAttributesArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransitionAttributes *TransitionAttributesArchive `protobuf:"bytes,1,opt,name=transition_attributes,json=transitionAttributes" json:"transition_attributes,omitempty"`
	Unset                *bool                        `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
}

func (x *SpecSetTransitionAttributesArchive) Reset() {
	*x = SpecSetTransitionAttributesArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KNArchives_sos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecSetTransitionAttributesArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecSetTransitionAttributesArchive) ProtoMessage() {}

func (x *SpecSetTransitionAttributesArchive) ProtoReflect() protoreflect.Message {
	mi := &file_KNArchives_sos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecSetTransitionAttributesArchive.ProtoReflect.Descriptor instead.
func (*SpecSetTransitionAttributesArchive) Descriptor() ([]byte, []int) {
	return file_KNArchives_sos_proto_rawDescGZIP(), []int{0}
}

func (x *SpecSetTransitionAttributesArchive) GetTransitionAttributes() *TransitionAttributesArchive {
	if x != nil {
		return x.TransitionAttributes
	}
	return nil
}

func (x *SpecSetTransitionAttributesArchive) GetUnset() bool {
	if x != nil && x.Unset != nil {
		return *x.Unset
	}
	return false
}

type SpecTransitionAttributesArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpecSetTransitionAttributes *SpecSetTransitionAttributesArchive `protobuf:"bytes,1,opt,name=spec_set_transition_attributes,json=specSetTransitionAttributes" json:"spec_set_transition_attributes,omitempty"`
}

func (x *SpecTransitionAttributesArchive) Reset() {
	*x = SpecTransitionAttributesArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KNArchives_sos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecTransitionAttributesArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecTransitionAttributesArchive) ProtoMessage() {}

func (x *SpecTransitionAttributesArchive) ProtoReflect() protoreflect.Message {
	mi := &file_KNArchives_sos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecTransitionAttributesArchive.ProtoReflect.Descriptor instead.
func (*SpecTransitionAttributesArchive) Descriptor() ([]byte, []int) {
	return file_KNArchives_sos_proto_rawDescGZIP(), []int{1}
}

func (x *SpecTransitionAttributesArchive) GetSpecSetTransitionAttributes() *SpecSetTransitionAttributesArchive {
	if x != nil {
		return x.SpecSetTransitionAttributes
	}
	return nil
}

type SlideStylePropertyChangeSetArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fill                     *SpecFillArchive                 `protobuf:"bytes,1,opt,name=fill" json:"fill,omitempty"`
	FillUndefined            *bool                            `protobuf:"varint,2,opt,name=fill_undefined,json=fillUndefined" json:"fill_undefined,omitempty"`
	SlideTransition          *SpecTransitionAttributesArchive `protobuf:"bytes,3,opt,name=slide_transition,json=slideTransition" json:"slide_transition,omitempty"`
	SlideTransitionUndefined *bool                            `protobuf:"varint,4,opt,name=slide_transition_undefined,json=slideTransitionUndefined" json:"slide_transition_undefined,omitempty"`
}

func (x *SlideStylePropertyChangeSetArchive) Reset() {
	*x = SlideStylePropertyChangeSetArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KNArchives_sos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlideStylePropertyChangeSetArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlideStylePropertyChangeSetArchive) ProtoMessage() {}

func (x *SlideStylePropertyChangeSetArchive) ProtoReflect() protoreflect.Message {
	mi := &file_KNArchives_sos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlideStylePropertyChangeSetArchive.ProtoReflect.Descriptor instead.
func (*SlideStylePropertyChangeSetArchive) Descriptor() ([]byte, []int) {
	return file_KNArchives_sos_proto_rawDescGZIP(), []int{2}
}

func (x *SlideStylePropertyChangeSetArchive) GetFill() *SpecFillArchive {
	if x != nil {
		return x.Fill
	}
	return nil
}

func (x *SlideStylePropertyChangeSetArchive) GetFillUndefined() bool {
	if x != nil && x.FillUndefined != nil {
		return *x.FillUndefined
	}
	return false
}

func (x *SlideStylePropertyChangeSetArchive) GetSlideTransition() *SpecTransitionAttributesArchive {
	if x != nil {
		return x.SlideTransition
	}
	return nil
}

func (x *SlideStylePropertyChangeSetArchive) GetSlideTransitionUndefined() bool {
	if x != nil && x.SlideTransitionUndefined != nil {
		return *x.SlideTransitionUndefined
	}
	return false
}

var File_KNArchives_sos_proto protoreflect.FileDescriptor

var file_KNArchives_sos_proto_rawDesc = []byte{
	0x0a, 0x14, 0x4b, 0x4e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x73, 0x5f, 0x73, 0x6f, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x4b, 0x4e, 0x53, 0x4f, 0x53, 0x1a, 0x10, 0x4b,
	0x4e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x15, 0x54, 0x53, 0x44, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x73, 0x5f, 0x73, 0x6f, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x22, 0x53, 0x70, 0x65, 0x63, 0x53,
	0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x54, 0x0a,
	0x15, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x4b,
	0x4e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x14, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x08, 0x52, 0x05, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x22, 0x91, 0x01, 0x0a, 0x1f, 0x53, 0x70,
	0x65, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x6e, 0x0a,
	0x1e, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x4b, 0x4e, 0x53, 0x4f, 0x53, 0x2e, 0x53, 0x70,
	0x65, 0x63, 0x53, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x52, 0x1b, 0x73, 0x70, 0x65, 0x63, 0x53, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x22, 0x89, 0x02,
	0x0a, 0x22, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x74, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x54, 0x53, 0x44, 0x53, 0x4f, 0x53, 0x2e, 0x53, 0x70, 0x65, 0x63,
	0x46, 0x69, 0x6c, 0x6c, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c,
	0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x6c, 0x5f, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x66, 0x69, 0x6c, 0x6c, 0x55,
	0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x51, 0x0a, 0x10, 0x73, 0x6c, 0x69, 0x64,
	0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x4b, 0x4e, 0x53, 0x4f, 0x53, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x0f, 0x73, 0x6c, 0x69, 0x64,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x1a, 0x73,
	0x6c, 0x69, 0x64, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x18, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x6b,
	0x70, 0x62,
}

var (
	file_KNArchives_sos_proto_rawDescOnce sync.Once
	file_KNArchives_sos_proto_rawDescData = file_KNArchives_sos_proto_rawDesc
)

func file_KNArchives_sos_proto_rawDescGZIP() []byte {
	file_KNArchives_sos_proto_rawDescOnce.Do(func() {
		file_KNArchives_sos_proto_rawDescData = protoimpl.X.CompressGZIP(file_KNArchives_sos_proto_rawDescData)
	})
	return file_KNArchives_sos_proto_rawDescData
}

var file_KNArchives_sos_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_KNArchives_sos_proto_goTypes = []interface{}{
	(*SpecSetTransitionAttributesArchive)(nil), // 0: KNSOS.SpecSetTransitionAttributesArchive
	(*SpecTransitionAttributesArchive)(nil),    // 1: KNSOS.SpecTransitionAttributesArchive
	(*SlideStylePropertyChangeSetArchive)(nil), // 2: KNSOS.SlideStylePropertyChangeSetArchive
	(*TransitionAttributesArchive)(nil),        // 3: KN.TransitionAttributesArchive
	(*SpecFillArchive)(nil),                    // 4: TSDSOS.SpecFillArchive
}
var file_KNArchives_sos_proto_depIdxs = []int32{
	3, // 0: KNSOS.SpecSetTransitionAttributesArchive.transition_attributes:type_name -> KN.TransitionAttributesArchive
	0, // 1: KNSOS.SpecTransitionAttributesArchive.spec_set_transition_attributes:type_name -> KNSOS.SpecSetTransitionAttributesArchive
	4, // 2: KNSOS.SlideStylePropertyChangeSetArchive.fill:type_name -> TSDSOS.SpecFillArchive
	1, // 3: KNSOS.SlideStylePropertyChangeSetArchive.slide_transition:type_name -> KNSOS.SpecTransitionAttributesArchive
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_KNArchives_sos_proto_init() }
func file_KNArchives_sos_proto_init() {
	if File_KNArchives_sos_proto != nil {
		return
	}
	file_KNArchives_proto_init()
	file_TSDArchives_sos_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_KNArchives_sos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecSetTransitionAttributesArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KNArchives_sos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecTransitionAttributesArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KNArchives_sos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlideStylePropertyChangeSetArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_KNArchives_sos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_KNArchives_sos_proto_goTypes,
		DependencyIndexes: file_KNArchives_sos_proto_depIdxs,
		MessageInfos:      file_KNArchives_sos_proto_msgTypes,
	}.Build()
	File_KNArchives_sos_proto = out.File
	file_KNArchives_sos_proto_rawDesc = nil
	file_KNArchives_sos_proto_goTypes = nil
	file_KNArchives_sos_proto_depIdxs = nil
}
