// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: KNCommandArchives_sos.proto

package kpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InducedVerifyDocumentWithServerCommandArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Super                            *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	SlideNodeIdList                  []*UUID         `protobuf:"bytes,2,rep,name=slide_node_id_list,json=slideNodeIdList" json:"slide_node_id_list,omitempty"`
	SlideNodeIdListUndefined         *bool           `protobuf:"varint,3,opt,name=slide_node_id_list_undefined,json=slideNodeIdListUndefined" json:"slide_node_id_list_undefined,omitempty"`
	TemplateSlideNodeIdList          []*UUID         `protobuf:"bytes,4,rep,name=template_slide_node_id_list,json=templateSlideNodeIdList" json:"template_slide_node_id_list,omitempty"`
	TemplateSlideNodeIdListUndefined *bool           `protobuf:"varint,5,opt,name=template_slide_node_id_list_undefined,json=templateSlideNodeIdListUndefined" json:"template_slide_node_id_list_undefined,omitempty"`
}

func (x *InducedVerifyDocumentWithServerCommandArchive) Reset() {
	*x = InducedVerifyDocumentWithServerCommandArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KNCommandArchives_sos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InducedVerifyDocumentWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InducedVerifyDocumentWithServerCommandArchive) ProtoMessage() {}

func (x *InducedVerifyDocumentWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_KNCommandArchives_sos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InducedVerifyDocumentWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*InducedVerifyDocumentWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_KNCommandArchives_sos_proto_rawDescGZIP(), []int{0}
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetSuper() *CommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetSlideNodeIdList() []*UUID {
	if x != nil {
		return x.SlideNodeIdList
	}
	return nil
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetSlideNodeIdListUndefined() bool {
	if x != nil && x.SlideNodeIdListUndefined != nil {
		return *x.SlideNodeIdListUndefined
	}
	return false
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetTemplateSlideNodeIdList() []*UUID {
	if x != nil {
		return x.TemplateSlideNodeIdList
	}
	return nil
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetTemplateSlideNodeIdListUndefined() bool {
	if x != nil && x.TemplateSlideNodeIdListUndefined != nil {
		return *x.TemplateSlideNodeIdListUndefined
	}
	return false
}

type KNInducedVerifyDrawableZOrdersWithServerCommandArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Super *TSAInducedVerifyDrawableZOrdersWithServerCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
}

func (x *KNInducedVerifyDrawableZOrdersWithServerCommandArchive) Reset() {
	*x = KNInducedVerifyDrawableZOrdersWithServerCommandArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KNCommandArchives_sos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KNInducedVerifyDrawableZOrdersWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KNInducedVerifyDrawableZOrdersWithServerCommandArchive) ProtoMessage() {}

func (x *KNInducedVerifyDrawableZOrdersWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_KNCommandArchives_sos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KNInducedVerifyDrawableZOrdersWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*KNInducedVerifyDrawableZOrdersWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_KNCommandArchives_sos_proto_rawDescGZIP(), []int{1}
}

func (x *KNInducedVerifyDrawableZOrdersWithServerCommandArchive) GetSuper() *TSAInducedVerifyDrawableZOrdersWithServerCommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

type CommandSlideReapplyTemplateSlideArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Super *CommandReapplyMasterArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
}

func (x *CommandSlideReapplyTemplateSlideArchive) Reset() {
	*x = CommandSlideReapplyTemplateSlideArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KNCommandArchives_sos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandSlideReapplyTemplateSlideArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandSlideReapplyTemplateSlideArchive) ProtoMessage() {}

func (x *CommandSlideReapplyTemplateSlideArchive) ProtoReflect() protoreflect.Message {
	mi := &file_KNCommandArchives_sos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandSlideReapplyTemplateSlideArchive.ProtoReflect.Descriptor instead.
func (*CommandSlideReapplyTemplateSlideArchive) Descriptor() ([]byte, []int) {
	return file_KNCommandArchives_sos_proto_rawDescGZIP(), []int{2}
}

func (x *CommandSlideReapplyTemplateSlideArchive) GetSuper() *CommandReapplyMasterArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

var File_KNCommandArchives_sos_proto protoreflect.FileDescriptor

var file_KNCommandArchives_sos_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x4b, 0x4e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x73, 0x5f, 0x73, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x4b,
	0x4e, 0x53, 0x4f, 0x53, 0x1a, 0x1c, 0x54, 0x53, 0x41, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x73, 0x5f, 0x73, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x11, 0x54, 0x53, 0x4b, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x54, 0x53, 0x50, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xec, 0x02, 0x0a, 0x2d, 0x49, 0x6e, 0x64,
	0x75, 0x63, 0x65, 0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x57, 0x69, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x75,
	0x70, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x53, 0x4b, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x05,
	0x73, 0x75, 0x70, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x12, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x5f, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x0f, 0x73, 0x6c,
	0x69, 0x64, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3e, 0x0a,
	0x1c, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x5f, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x18, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x47, 0x0a,
	0x1b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x5f,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x17, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x4f, 0x0a, 0x25, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x5f, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x20, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53,
	0x6c, 0x69, 0x64, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x6e,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x22, 0x8f, 0x01, 0x0a, 0x36, 0x4b, 0x4e, 0x49, 0x6e,
	0x64, 0x75, 0x63, 0x65, 0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x44, 0x72, 0x61, 0x77, 0x61,
	0x62, 0x6c, 0x65, 0x5a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x57, 0x69, 0x74, 0x68, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x12, 0x55, 0x0a, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0b, 0x32, 0x3f, 0x2e, 0x54, 0x53, 0x41, 0x53, 0x4f, 0x53, 0x2e, 0x54, 0x53, 0x41, 0x49, 0x6e,
	0x64, 0x75, 0x63, 0x65, 0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x44, 0x72, 0x61, 0x77, 0x61,
	0x62, 0x6c, 0x65, 0x5a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x57, 0x69, 0x74, 0x68, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x52, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x22, 0x64, 0x0a, 0x27, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x52, 0x65, 0x61, 0x70, 0x70, 0x6c, 0x79,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x12, 0x39, 0x0a, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x54, 0x53, 0x41, 0x53, 0x4f, 0x53, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x6b, 0x70, 0x62,
}

var (
	file_KNCommandArchives_sos_proto_rawDescOnce sync.Once
	file_KNCommandArchives_sos_proto_rawDescData = file_KNCommandArchives_sos_proto_rawDesc
)

func file_KNCommandArchives_sos_proto_rawDescGZIP() []byte {
	file_KNCommandArchives_sos_proto_rawDescOnce.Do(func() {
		file_KNCommandArchives_sos_proto_rawDescData = protoimpl.X.CompressGZIP(file_KNCommandArchives_sos_proto_rawDescData)
	})
	return file_KNCommandArchives_sos_proto_rawDescData
}

var file_KNCommandArchives_sos_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_KNCommandArchives_sos_proto_goTypes = []interface{}{
	(*InducedVerifyDocumentWithServerCommandArchive)(nil),           // 0: KNSOS.InducedVerifyDocumentWithServerCommandArchive
	(*KNInducedVerifyDrawableZOrdersWithServerCommandArchive)(nil),  // 1: KNSOS.KNInducedVerifyDrawableZOrdersWithServerCommandArchive
	(*CommandSlideReapplyTemplateSlideArchive)(nil),                 // 2: KNSOS.CommandSlideReapplyTemplateSlideArchive
	(*CommandArchive)(nil),                                          // 3: TSK.CommandArchive
	(*UUID)(nil),                                                    // 4: TSP.UUID
	(*TSAInducedVerifyDrawableZOrdersWithServerCommandArchive)(nil), // 5: TSASOS.TSAInducedVerifyDrawableZOrdersWithServerCommandArchive
	(*CommandReapplyMasterArchive)(nil),                             // 6: TSASOS.CommandReapplyMasterArchive
}
var file_KNCommandArchives_sos_proto_depIdxs = []int32{
	3, // 0: KNSOS.InducedVerifyDocumentWithServerCommandArchive.super:type_name -> TSK.CommandArchive
	4, // 1: KNSOS.InducedVerifyDocumentWithServerCommandArchive.slide_node_id_list:type_name -> TSP.UUID
	4, // 2: KNSOS.InducedVerifyDocumentWithServerCommandArchive.template_slide_node_id_list:type_name -> TSP.UUID
	5, // 3: KNSOS.KNInducedVerifyDrawableZOrdersWithServerCommandArchive.super:type_name -> TSASOS.TSAInducedVerifyDrawableZOrdersWithServerCommandArchive
	6, // 4: KNSOS.CommandSlideReapplyTemplateSlideArchive.super:type_name -> TSASOS.CommandReapplyMasterArchive
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_KNCommandArchives_sos_proto_init() }
func file_KNCommandArchives_sos_proto_init() {
	if File_KNCommandArchives_sos_proto != nil {
		return
	}
	file_TSACommandArchives_sos_proto_init()
	file_TSKArchives_proto_init()
	file_TSPMessages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_KNCommandArchives_sos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InducedVerifyDocumentWithServerCommandArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KNCommandArchives_sos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KNInducedVerifyDrawableZOrdersWithServerCommandArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KNCommandArchives_sos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandSlideReapplyTemplateSlideArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_KNCommandArchives_sos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_KNCommandArchives_sos_proto_goTypes,
		DependencyIndexes: file_KNCommandArchives_sos_proto_depIdxs,
		MessageInfos:      file_KNCommandArchives_sos_proto_msgTypes,
	}.Build()
	File_KNCommandArchives_sos_proto = out.File
	file_KNCommandArchives_sos_proto_rawDesc = nil
	file_KNCommandArchives_sos_proto_goTypes = nil
	file_KNCommandArchives_sos_proto_depIdxs = nil
}
