// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: TSACommandArchives_sos.proto

package kpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TSAInducedVerifyDrawableZOrdersWithServerCommandArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Super                              *CommandArchive              `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	ServerDrawableZOrderLists          []*DrawableZOrderListArchive `protobuf:"bytes,2,rep,name=server_drawable_z_order_lists,json=serverDrawableZOrderLists" json:"server_drawable_z_order_lists,omitempty"`
	ServerDrawableZOrderListsUndefined *bool                        `protobuf:"varint,3,opt,name=server_drawable_z_order_lists_undefined,json=serverDrawableZOrderListsUndefined" json:"server_drawable_z_order_lists_undefined,omitempty"`
}

func (x *TSAInducedVerifyDrawableZOrdersWithServerCommandArchive) Reset() {
	*x = TSAInducedVerifyDrawableZOrdersWithServerCommandArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSACommandArchives_sos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TSAInducedVerifyDrawableZOrdersWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TSAInducedVerifyDrawableZOrdersWithServerCommandArchive) ProtoMessage() {}

func (x *TSAInducedVerifyDrawableZOrdersWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSACommandArchives_sos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TSAInducedVerifyDrawableZOrdersWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*TSAInducedVerifyDrawableZOrdersWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_TSACommandArchives_sos_proto_rawDescGZIP(), []int{0}
}

func (x *TSAInducedVerifyDrawableZOrdersWithServerCommandArchive) GetSuper() *CommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *TSAInducedVerifyDrawableZOrdersWithServerCommandArchive) GetServerDrawableZOrderLists() []*DrawableZOrderListArchive {
	if x != nil {
		return x.ServerDrawableZOrderLists
	}
	return nil
}

func (x *TSAInducedVerifyDrawableZOrdersWithServerCommandArchive) GetServerDrawableZOrderListsUndefined() bool {
	if x != nil && x.ServerDrawableZOrderListsUndefined != nil {
		return *x.ServerDrawableZOrderListsUndefined
	}
	return false
}

type PropagateMasterChangeCommandArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Super                                    *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	UuidsOfPreviouslyVisitedObjects          []*UUID         `protobuf:"bytes,2,rep,name=uuids_of_previously_visited_objects,json=uuidsOfPreviouslyVisitedObjects" json:"uuids_of_previously_visited_objects,omitempty"`
	UuidsOfPreviouslyVisitedObjectsUndefined *bool           `protobuf:"varint,3,opt,name=uuids_of_previously_visited_objects_undefined,json=uuidsOfPreviouslyVisitedObjectsUndefined" json:"uuids_of_previously_visited_objects_undefined,omitempty"`
}

func (x *PropagateMasterChangeCommandArchive) Reset() {
	*x = PropagateMasterChangeCommandArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSACommandArchives_sos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropagateMasterChangeCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagateMasterChangeCommandArchive) ProtoMessage() {}

func (x *PropagateMasterChangeCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSACommandArchives_sos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagateMasterChangeCommandArchive.ProtoReflect.Descriptor instead.
func (*PropagateMasterChangeCommandArchive) Descriptor() ([]byte, []int) {
	return file_TSACommandArchives_sos_proto_rawDescGZIP(), []int{1}
}

func (x *PropagateMasterChangeCommandArchive) GetSuper() *CommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *PropagateMasterChangeCommandArchive) GetUuidsOfPreviouslyVisitedObjects() []*UUID {
	if x != nil {
		return x.UuidsOfPreviouslyVisitedObjects
	}
	return nil
}

func (x *PropagateMasterChangeCommandArchive) GetUuidsOfPreviouslyVisitedObjectsUndefined() bool {
	if x != nil && x.UuidsOfPreviouslyVisitedObjectsUndefined != nil {
		return *x.UuidsOfPreviouslyVisitedObjectsUndefined
	}
	return false
}

type CommandReapplyMasterArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Super                 *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	ItemsToVisit          []*UUID         `protobuf:"bytes,2,rep,name=items_to_visit,json=itemsToVisit" json:"items_to_visit,omitempty"`
	ItemsToVisitUndefined *bool           `protobuf:"varint,3,opt,name=items_to_visit_undefined,json=itemsToVisitUndefined" json:"items_to_visit_undefined,omitempty"`
	IsUndo                *bool           `protobuf:"varint,4,req,name=is_undo,json=isUndo" json:"is_undo,omitempty"`
}

func (x *CommandReapplyMasterArchive) Reset() {
	*x = CommandReapplyMasterArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSACommandArchives_sos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandReapplyMasterArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandReapplyMasterArchive) ProtoMessage() {}

func (x *CommandReapplyMasterArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSACommandArchives_sos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandReapplyMasterArchive.ProtoReflect.Descriptor instead.
func (*CommandReapplyMasterArchive) Descriptor() ([]byte, []int) {
	return file_TSACommandArchives_sos_proto_rawDescGZIP(), []int{2}
}

func (x *CommandReapplyMasterArchive) GetSuper() *CommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *CommandReapplyMasterArchive) GetItemsToVisit() []*UUID {
	if x != nil {
		return x.ItemsToVisit
	}
	return nil
}

func (x *CommandReapplyMasterArchive) GetItemsToVisitUndefined() bool {
	if x != nil && x.ItemsToVisitUndefined != nil {
		return *x.ItemsToVisitUndefined
	}
	return false
}

func (x *CommandReapplyMasterArchive) GetIsUndo() bool {
	if x != nil && x.IsUndo != nil {
		return *x.IsUndo
	}
	return false
}

type VerifyDocumentWithServerCommandArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Super *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
}

func (x *VerifyDocumentWithServerCommandArchive) Reset() {
	*x = VerifyDocumentWithServerCommandArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSACommandArchives_sos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyDocumentWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyDocumentWithServerCommandArchive) ProtoMessage() {}

func (x *VerifyDocumentWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSACommandArchives_sos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyDocumentWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*VerifyDocumentWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_TSACommandArchives_sos_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyDocumentWithServerCommandArchive) GetSuper() *CommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

type VerifyDrawableZOrdersWithServerCommandArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Super                   *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	DrawableIdList          []*UUID         `protobuf:"bytes,2,rep,name=drawable_id_list,json=drawableIdList" json:"drawable_id_list,omitempty"`
	DrawableIdListUndefined *bool           `protobuf:"varint,3,opt,name=drawable_id_list_undefined,json=drawableIdListUndefined" json:"drawable_id_list_undefined,omitempty"`
}

func (x *VerifyDrawableZOrdersWithServerCommandArchive) Reset() {
	*x = VerifyDrawableZOrdersWithServerCommandArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSACommandArchives_sos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyDrawableZOrdersWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyDrawableZOrdersWithServerCommandArchive) ProtoMessage() {}

func (x *VerifyDrawableZOrdersWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSACommandArchives_sos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyDrawableZOrdersWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*VerifyDrawableZOrdersWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_TSACommandArchives_sos_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyDrawableZOrdersWithServerCommandArchive) GetSuper() *CommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *VerifyDrawableZOrdersWithServerCommandArchive) GetDrawableIdList() []*UUID {
	if x != nil {
		return x.DrawableIdList
	}
	return nil
}

func (x *VerifyDrawableZOrdersWithServerCommandArchive) GetDrawableIdListUndefined() bool {
	if x != nil && x.DrawableIdListUndefined != nil {
		return *x.DrawableIdListUndefined
	}
	return false
}

type VerifyObjectsWithServerCommandArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Super                 *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	ObjectIdList          []*UUID         `protobuf:"bytes,2,rep,name=object_id_list,json=objectIdList" json:"object_id_list,omitempty"`
	ObjectIdListUndefined *bool           `protobuf:"varint,3,opt,name=object_id_list_undefined,json=objectIdListUndefined" json:"object_id_list_undefined,omitempty"`
}

func (x *VerifyObjectsWithServerCommandArchive) Reset() {
	*x = VerifyObjectsWithServerCommandArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSACommandArchives_sos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyObjectsWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyObjectsWithServerCommandArchive) ProtoMessage() {}

func (x *VerifyObjectsWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSACommandArchives_sos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyObjectsWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*VerifyObjectsWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_TSACommandArchives_sos_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyObjectsWithServerCommandArchive) GetSuper() *CommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *VerifyObjectsWithServerCommandArchive) GetObjectIdList() []*UUID {
	if x != nil {
		return x.ObjectIdList
	}
	return nil
}

func (x *VerifyObjectsWithServerCommandArchive) GetObjectIdListUndefined() bool {
	if x != nil && x.ObjectIdListUndefined != nil {
		return *x.ObjectIdListUndefined
	}
	return false
}

type VerifyTransformHistoryWithServerCommandArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Super         *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	SequenceStart *int32          `protobuf:"varint,2,req,name=sequence_start,json=sequenceStart" json:"sequence_start,omitempty"`
	SequenceEnd   *int32          `protobuf:"varint,3,req,name=sequence_end,json=sequenceEnd" json:"sequence_end,omitempty"`
}

func (x *VerifyTransformHistoryWithServerCommandArchive) Reset() {
	*x = VerifyTransformHistoryWithServerCommandArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSACommandArchives_sos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyTransformHistoryWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTransformHistoryWithServerCommandArchive) ProtoMessage() {}

func (x *VerifyTransformHistoryWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSACommandArchives_sos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTransformHistoryWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*VerifyTransformHistoryWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_TSACommandArchives_sos_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyTransformHistoryWithServerCommandArchive) GetSuper() *CommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *VerifyTransformHistoryWithServerCommandArchive) GetSequenceStart() int32 {
	if x != nil && x.SequenceStart != nil {
		return *x.SequenceStart
	}
	return 0
}

func (x *VerifyTransformHistoryWithServerCommandArchive) GetSequenceEnd() int32 {
	if x != nil && x.SequenceEnd != nil {
		return *x.SequenceEnd
	}
	return 0
}

var File_TSACommandArchives_sos_proto protoreflect.FileDescriptor

var file_TSACommandArchives_sos_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x54, 0x53, 0x41, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x73, 0x5f, 0x73, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x54, 0x53, 0x41, 0x53, 0x4f, 0x53, 0x1a, 0x15, 0x54, 0x53, 0x41, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x73, 0x5f, 0x73, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x54,
	0x53, 0x4b, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x11, 0x54, 0x53, 0x50, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x02, 0x0a, 0x37, 0x54, 0x53, 0x41, 0x49, 0x6e, 0x64, 0x75, 0x63,
	0x65, 0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x44, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65,
	0x5a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x57, 0x69, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12,
	0x29, 0x0a, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x54, 0x53, 0x4b, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x52, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x12, 0x63, 0x0a, 0x1d, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x7a, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x54, 0x53, 0x41, 0x53, 0x4f, 0x53, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x61,
	0x62, 0x6c, 0x65, 0x5a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x52, 0x19, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x72, 0x61, 0x77,
	0x61, 0x62, 0x6c, 0x65, 0x5a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x12,
	0x53, 0x0a, 0x27, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62,
	0x6c, 0x65, 0x5f, 0x7a, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x73,
	0x5f, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x22, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65,
	0x5a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x55, 0x6e, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x65, 0x64, 0x22, 0x8a, 0x02, 0x0a, 0x23, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x29, 0x0a, 0x05,
	0x73, 0x75, 0x70, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x53,
	0x4b, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x52, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x12, 0x57, 0x0a, 0x23, 0x75, 0x75, 0x69, 0x64, 0x73,
	0x5f, 0x6f, 0x66, 0x5f, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x6c, 0x79, 0x5f, 0x76,
	0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52,
	0x1f, 0x75, 0x75, 0x69, 0x64, 0x73, 0x4f, 0x66, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73,
	0x6c, 0x79, 0x56, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x12, 0x5f, 0x0a, 0x2d, 0x75, 0x75, 0x69, 0x64, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x70, 0x72, 0x65,
	0x76, 0x69, 0x6f, 0x75, 0x73, 0x6c, 0x79, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x5f,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x5f, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x28, 0x75, 0x75, 0x69, 0x64, 0x73, 0x4f, 0x66,
	0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x6c, 0x79, 0x56, 0x69, 0x73, 0x69, 0x74, 0x65,
	0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65,
	0x64, 0x22, 0xcb, 0x01, 0x0a, 0x1b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x61,
	0x70, 0x70, 0x6c, 0x79, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x54, 0x53, 0x4b, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x0e,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x5f, 0x74, 0x6f, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52,
	0x0c, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x54, 0x6f, 0x56, 0x69, 0x73, 0x69, 0x74, 0x12, 0x37, 0x0a,
	0x18, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x5f, 0x74, 0x6f, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x74, 0x5f,
	0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x15, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x54, 0x6f, 0x56, 0x69, 0x73, 0x69, 0x74, 0x55, 0x6e, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x75, 0x6e, 0x64,
	0x6f, 0x18, 0x04, 0x20, 0x02, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x55, 0x6e, 0x64, 0x6f, 0x22,
	0x53, 0x0a, 0x26, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x57, 0x69, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x75, 0x70,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x53, 0x4b, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x05, 0x73,
	0x75, 0x70, 0x65, 0x72, 0x22, 0xcc, 0x01, 0x0a, 0x2d, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x44,
	0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65, 0x5a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x57, 0x69,
	0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x53, 0x4b, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x05, 0x73, 0x75, 0x70, 0x65,
	0x72, 0x12, 0x33, 0x0a, 0x10, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x54, 0x53,
	0x50, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x0e, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65,
	0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x1a, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x75, 0x6e, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x17, 0x64, 0x72, 0x61, 0x77,
	0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x65, 0x64, 0x22, 0xbc, 0x01, 0x0a, 0x25, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x57, 0x69, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x29, 0x0a,
	0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54,
	0x53, 0x4b, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x52, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x0e, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x54, 0x53, 0x50, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x0c, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x18, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x75, 0x6e, 0x64, 0x65,
	0x66, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x65, 0x64, 0x22, 0xa5, 0x01, 0x0a, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x57, 0x69, 0x74,
	0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x53, 0x4b, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x05, 0x73, 0x75, 0x70, 0x65, 0x72,
	0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0b, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x6e, 0x64, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x6b, 0x70, 0x62,
}

var (
	file_TSACommandArchives_sos_proto_rawDescOnce sync.Once
	file_TSACommandArchives_sos_proto_rawDescData = file_TSACommandArchives_sos_proto_rawDesc
)

func file_TSACommandArchives_sos_proto_rawDescGZIP() []byte {
	file_TSACommandArchives_sos_proto_rawDescOnce.Do(func() {
		file_TSACommandArchives_sos_proto_rawDescData = protoimpl.X.CompressGZIP(file_TSACommandArchives_sos_proto_rawDescData)
	})
	return file_TSACommandArchives_sos_proto_rawDescData
}

var file_TSACommandArchives_sos_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_TSACommandArchives_sos_proto_goTypes = []interface{}{
	(*TSAInducedVerifyDrawableZOrdersWithServerCommandArchive)(nil), // 0: TSASOS.TSAInducedVerifyDrawableZOrdersWithServerCommandArchive
	(*PropagateMasterChangeCommandArchive)(nil),                     // 1: TSASOS.PropagateMasterChangeCommandArchive
	(*CommandReapplyMasterArchive)(nil),                             // 2: TSASOS.CommandReapplyMasterArchive
	(*VerifyDocumentWithServerCommandArchive)(nil),                  // 3: TSASOS.VerifyDocumentWithServerCommandArchive
	(*VerifyDrawableZOrdersWithServerCommandArchive)(nil),           // 4: TSASOS.VerifyDrawableZOrdersWithServerCommandArchive
	(*VerifyObjectsWithServerCommandArchive)(nil),                   // 5: TSASOS.VerifyObjectsWithServerCommandArchive
	(*VerifyTransformHistoryWithServerCommandArchive)(nil),          // 6: TSASOS.VerifyTransformHistoryWithServerCommandArchive
	(*CommandArchive)(nil),                                          // 7: TSK.CommandArchive
	(*DrawableZOrderListArchive)(nil),                               // 8: TSASOS.DrawableZOrderListArchive
	(*UUID)(nil),                                                    // 9: TSP.UUID
}
var file_TSACommandArchives_sos_proto_depIdxs = []int32{
	7,  // 0: TSASOS.TSAInducedVerifyDrawableZOrdersWithServerCommandArchive.super:type_name -> TSK.CommandArchive
	8,  // 1: TSASOS.TSAInducedVerifyDrawableZOrdersWithServerCommandArchive.server_drawable_z_order_lists:type_name -> TSASOS.DrawableZOrderListArchive
	7,  // 2: TSASOS.PropagateMasterChangeCommandArchive.super:type_name -> TSK.CommandArchive
	9,  // 3: TSASOS.PropagateMasterChangeCommandArchive.uuids_of_previously_visited_objects:type_name -> TSP.UUID
	7,  // 4: TSASOS.CommandReapplyMasterArchive.super:type_name -> TSK.CommandArchive
	9,  // 5: TSASOS.CommandReapplyMasterArchive.items_to_visit:type_name -> TSP.UUID
	7,  // 6: TSASOS.VerifyDocumentWithServerCommandArchive.super:type_name -> TSK.CommandArchive
	7,  // 7: TSASOS.VerifyDrawableZOrdersWithServerCommandArchive.super:type_name -> TSK.CommandArchive
	9,  // 8: TSASOS.VerifyDrawableZOrdersWithServerCommandArchive.drawable_id_list:type_name -> TSP.UUID
	7,  // 9: TSASOS.VerifyObjectsWithServerCommandArchive.super:type_name -> TSK.CommandArchive
	9,  // 10: TSASOS.VerifyObjectsWithServerCommandArchive.object_id_list:type_name -> TSP.UUID
	7,  // 11: TSASOS.VerifyTransformHistoryWithServerCommandArchive.super:type_name -> TSK.CommandArchive
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_TSACommandArchives_sos_proto_init() }
func file_TSACommandArchives_sos_proto_init() {
	if File_TSACommandArchives_sos_proto != nil {
		return
	}
	file_TSAArchives_sos_proto_init()
	file_TSKArchives_proto_init()
	file_TSPMessages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_TSACommandArchives_sos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TSAInducedVerifyDrawableZOrdersWithServerCommandArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSACommandArchives_sos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropagateMasterChangeCommandArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSACommandArchives_sos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandReapplyMasterArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSACommandArchives_sos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyDocumentWithServerCommandArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSACommandArchives_sos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyDrawableZOrdersWithServerCommandArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSACommandArchives_sos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyObjectsWithServerCommandArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSACommandArchives_sos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyTransformHistoryWithServerCommandArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TSACommandArchives_sos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TSACommandArchives_sos_proto_goTypes,
		DependencyIndexes: file_TSACommandArchives_sos_proto_depIdxs,
		MessageInfos:      file_TSACommandArchives_sos_proto_msgTypes,
	}.Build()
	File_TSACommandArchives_sos_proto = out.File
	file_TSACommandArchives_sos_proto_rawDesc = nil
	file_TSACommandArchives_sos_proto_goTypes = nil
	file_TSACommandArchives_sos_proto_depIdxs = nil
}
