// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: TSSArchives_sos.proto

package kpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpecSetBoolArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *bool `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	Unset *bool `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
}

func (x *SpecSetBoolArchive) Reset() {
	*x = SpecSetBoolArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSSArchives_sos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecSetBoolArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecSetBoolArchive) ProtoMessage() {}

func (x *SpecSetBoolArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecSetBoolArchive.ProtoReflect.Descriptor instead.
func (*SpecSetBoolArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{0}
}

func (x *SpecSetBoolArchive) GetValue() bool {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return false
}

func (x *SpecSetBoolArchive) GetUnset() bool {
	if x != nil && x.Unset != nil {
		return *x.Unset
	}
	return false
}

type SpecSetColorArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color *Color `protobuf:"bytes,1,opt,name=color" json:"color,omitempty"`
	Unset *bool  `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
}

func (x *SpecSetColorArchive) Reset() {
	*x = SpecSetColorArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSSArchives_sos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecSetColorArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecSetColorArchive) ProtoMessage() {}

func (x *SpecSetColorArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecSetColorArchive.ProtoReflect.Descriptor instead.
func (*SpecSetColorArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{1}
}

func (x *SpecSetColorArchive) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *SpecSetColorArchive) GetUnset() bool {
	if x != nil && x.Unset != nil {
		return *x.Unset
	}
	return false
}

type SpecSetDoubleArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *float64 `protobuf:"fixed64,1,req,name=value" json:"value,omitempty"`
	Unset *bool    `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
}

func (x *SpecSetDoubleArchive) Reset() {
	*x = SpecSetDoubleArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSSArchives_sos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecSetDoubleArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecSetDoubleArchive) ProtoMessage() {}

func (x *SpecSetDoubleArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecSetDoubleArchive.ProtoReflect.Descriptor instead.
func (*SpecSetDoubleArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{2}
}

func (x *SpecSetDoubleArchive) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *SpecSetDoubleArchive) GetUnset() bool {
	if x != nil && x.Unset != nil {
		return *x.Unset
	}
	return false
}

type SpecSetIntegerArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *int32 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	Unset *bool  `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
}

func (x *SpecSetIntegerArchive) Reset() {
	*x = SpecSetIntegerArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSSArchives_sos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecSetIntegerArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecSetIntegerArchive) ProtoMessage() {}

func (x *SpecSetIntegerArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecSetIntegerArchive.ProtoReflect.Descriptor instead.
func (*SpecSetIntegerArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{3}
}

func (x *SpecSetIntegerArchive) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *SpecSetIntegerArchive) GetUnset() bool {
	if x != nil && x.Unset != nil {
		return *x.Unset
	}
	return false
}

type SpecSetStringArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Unset *bool   `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
}

func (x *SpecSetStringArchive) Reset() {
	*x = SpecSetStringArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSSArchives_sos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecSetStringArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecSetStringArchive) ProtoMessage() {}

func (x *SpecSetStringArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecSetStringArchive.ProtoReflect.Descriptor instead.
func (*SpecSetStringArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{4}
}

func (x *SpecSetStringArchive) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *SpecSetStringArchive) GetUnset() bool {
	if x != nil && x.Unset != nil {
		return *x.Unset
	}
	return false
}

type SpecBoolArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpecSetBool *SpecSetBoolArchive `protobuf:"bytes,1,opt,name=spec_set_bool,json=specSetBool" json:"spec_set_bool,omitempty"`
}

func (x *SpecBoolArchive) Reset() {
	*x = SpecBoolArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSSArchives_sos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecBoolArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecBoolArchive) ProtoMessage() {}

func (x *SpecBoolArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecBoolArchive.ProtoReflect.Descriptor instead.
func (*SpecBoolArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{5}
}

func (x *SpecBoolArchive) GetSpecSetBool() *SpecSetBoolArchive {
	if x != nil {
		return x.SpecSetBool
	}
	return nil
}

type SpecColorArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpecSetColor *SpecSetColorArchive `protobuf:"bytes,1,opt,name=spec_set_color,json=specSetColor" json:"spec_set_color,omitempty"`
}

func (x *SpecColorArchive) Reset() {
	*x = SpecColorArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSSArchives_sos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecColorArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecColorArchive) ProtoMessage() {}

func (x *SpecColorArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecColorArchive.ProtoReflect.Descriptor instead.
func (*SpecColorArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{6}
}

func (x *SpecColorArchive) GetSpecSetColor() *SpecSetColorArchive {
	if x != nil {
		return x.SpecSetColor
	}
	return nil
}

type SpecDoubleArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpecSetDouble *SpecSetDoubleArchive `protobuf:"bytes,1,opt,name=spec_set_double,json=specSetDouble" json:"spec_set_double,omitempty"`
}

func (x *SpecDoubleArchive) Reset() {
	*x = SpecDoubleArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSSArchives_sos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecDoubleArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecDoubleArchive) ProtoMessage() {}

func (x *SpecDoubleArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecDoubleArchive.ProtoReflect.Descriptor instead.
func (*SpecDoubleArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{7}
}

func (x *SpecDoubleArchive) GetSpecSetDouble() *SpecSetDoubleArchive {
	if x != nil {
		return x.SpecSetDouble
	}
	return nil
}

type SpecIntegerArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpecSetInteger *SpecSetIntegerArchive `protobuf:"bytes,1,opt,name=spec_set_integer,json=specSetInteger" json:"spec_set_integer,omitempty"`
}

func (x *SpecIntegerArchive) Reset() {
	*x = SpecIntegerArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSSArchives_sos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecIntegerArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecIntegerArchive) ProtoMessage() {}

func (x *SpecIntegerArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecIntegerArchive.ProtoReflect.Descriptor instead.
func (*SpecIntegerArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{8}
}

func (x *SpecIntegerArchive) GetSpecSetInteger() *SpecSetIntegerArchive {
	if x != nil {
		return x.SpecSetInteger
	}
	return nil
}

type SpecStringArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpecSetString *SpecSetStringArchive `protobuf:"bytes,1,opt,name=spec_set_string,json=specSetString" json:"spec_set_string,omitempty"`
}

func (x *SpecStringArchive) Reset() {
	*x = SpecStringArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TSSArchives_sos_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecStringArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecStringArchive) ProtoMessage() {}

func (x *SpecStringArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecStringArchive.ProtoReflect.Descriptor instead.
func (*SpecStringArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{9}
}

func (x *SpecStringArchive) GetSpecSetString() *SpecSetStringArchive {
	if x != nil {
		return x.SpecSetString
	}
	return nil
}

var File_TSSArchives_sos_proto protoreflect.FileDescriptor

var file_TSSArchives_sos_proto_rawDesc = []byte{
	0x0a, 0x15, 0x54, 0x53, 0x53, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x73, 0x5f, 0x73, 0x6f,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x54, 0x53, 0x53, 0x53, 0x4f, 0x53, 0x1a,
	0x11, 0x54, 0x53, 0x50, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x40, 0x0a, 0x12, 0x53, 0x70, 0x65, 0x63, 0x53, 0x65, 0x74, 0x42, 0x6f, 0x6f,
	0x6c, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x05, 0x75,
	0x6e, 0x73, 0x65, 0x74, 0x22, 0x4d, 0x0a, 0x13, 0x53, 0x70, 0x65, 0x63, 0x53, 0x65, 0x74, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x53, 0x50,
	0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x05, 0x75, 0x6e,
	0x73, 0x65, 0x74, 0x22, 0x42, 0x0a, 0x14, 0x53, 0x70, 0x65, 0x63, 0x53, 0x65, 0x74, 0x44, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08,
	0x52, 0x05, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x22, 0x43, 0x0a, 0x15, 0x53, 0x70, 0x65, 0x63, 0x53,
	0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x05, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x22, 0x42, 0x0a, 0x14,
	0x53, 0x70, 0x65, 0x63, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e,
	0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x05, 0x75, 0x6e, 0x73, 0x65, 0x74,
	0x22, 0x51, 0x0a, 0x0f, 0x53, 0x70, 0x65, 0x63, 0x42, 0x6f, 0x6f, 0x6c, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x73, 0x65, 0x74, 0x5f,
	0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x54, 0x53, 0x53,
	0x53, 0x4f, 0x53, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x53, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x0b, 0x73, 0x70, 0x65, 0x63, 0x53, 0x65, 0x74, 0x42,
	0x6f, 0x6f, 0x6c, 0x22, 0x55, 0x0a, 0x10, 0x53, 0x70, 0x65, 0x63, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x5f,
	0x73, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x54, 0x53, 0x53, 0x53, 0x4f, 0x53, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x53, 0x65, 0x74,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x0c, 0x73, 0x70,
	0x65, 0x63, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x59, 0x0a, 0x11, 0x53, 0x70,
	0x65, 0x63, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12,
	0x44, 0x0a, 0x0f, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x64, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x54, 0x53, 0x53, 0x53, 0x4f,
	0x53, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x53, 0x65, 0x74, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x0d, 0x73, 0x70, 0x65, 0x63, 0x53, 0x65, 0x74, 0x44,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x22, 0x5d, 0x0a, 0x12, 0x53, 0x70, 0x65, 0x63, 0x49, 0x6e, 0x74,
	0x65, 0x67, 0x65, 0x72, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x73,
	0x70, 0x65, 0x63, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x54, 0x53, 0x53, 0x53, 0x4f, 0x53, 0x2e, 0x53,
	0x70, 0x65, 0x63, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x67, 0x65, 0x72, 0x22, 0x59, 0x0a, 0x11, 0x53, 0x70, 0x65, 0x63, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x73, 0x70, 0x65,
	0x63, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x54, 0x53, 0x53, 0x53, 0x4f, 0x53, 0x2e, 0x53, 0x70, 0x65, 0x63,
	0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x52, 0x0d, 0x73, 0x70, 0x65, 0x63, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x6b, 0x70, 0x62,
}

var (
	file_TSSArchives_sos_proto_rawDescOnce sync.Once
	file_TSSArchives_sos_proto_rawDescData = file_TSSArchives_sos_proto_rawDesc
)

func file_TSSArchives_sos_proto_rawDescGZIP() []byte {
	file_TSSArchives_sos_proto_rawDescOnce.Do(func() {
		file_TSSArchives_sos_proto_rawDescData = protoimpl.X.CompressGZIP(file_TSSArchives_sos_proto_rawDescData)
	})
	return file_TSSArchives_sos_proto_rawDescData
}

var file_TSSArchives_sos_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_TSSArchives_sos_proto_goTypes = []interface{}{
	(*SpecSetBoolArchive)(nil),    // 0: TSSSOS.SpecSetBoolArchive
	(*SpecSetColorArchive)(nil),   // 1: TSSSOS.SpecSetColorArchive
	(*SpecSetDoubleArchive)(nil),  // 2: TSSSOS.SpecSetDoubleArchive
	(*SpecSetIntegerArchive)(nil), // 3: TSSSOS.SpecSetIntegerArchive
	(*SpecSetStringArchive)(nil),  // 4: TSSSOS.SpecSetStringArchive
	(*SpecBoolArchive)(nil),       // 5: TSSSOS.SpecBoolArchive
	(*SpecColorArchive)(nil),      // 6: TSSSOS.SpecColorArchive
	(*SpecDoubleArchive)(nil),     // 7: TSSSOS.SpecDoubleArchive
	(*SpecIntegerArchive)(nil),    // 8: TSSSOS.SpecIntegerArchive
	(*SpecStringArchive)(nil),     // 9: TSSSOS.SpecStringArchive
	(*Color)(nil),                 // 10: TSP.Color
}
var file_TSSArchives_sos_proto_depIdxs = []int32{
	10, // 0: TSSSOS.SpecSetColorArchive.color:type_name -> TSP.Color
	0,  // 1: TSSSOS.SpecBoolArchive.spec_set_bool:type_name -> TSSSOS.SpecSetBoolArchive
	1,  // 2: TSSSOS.SpecColorArchive.spec_set_color:type_name -> TSSSOS.SpecSetColorArchive
	2,  // 3: TSSSOS.SpecDoubleArchive.spec_set_double:type_name -> TSSSOS.SpecSetDoubleArchive
	3,  // 4: TSSSOS.SpecIntegerArchive.spec_set_integer:type_name -> TSSSOS.SpecSetIntegerArchive
	4,  // 5: TSSSOS.SpecStringArchive.spec_set_string:type_name -> TSSSOS.SpecSetStringArchive
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_TSSArchives_sos_proto_init() }
func file_TSSArchives_sos_proto_init() {
	if File_TSSArchives_sos_proto != nil {
		return
	}
	file_TSPMessages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_TSSArchives_sos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecSetBoolArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSSArchives_sos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecSetColorArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSSArchives_sos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecSetDoubleArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSSArchives_sos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecSetIntegerArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSSArchives_sos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecSetStringArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSSArchives_sos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecBoolArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSSArchives_sos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecColorArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSSArchives_sos_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecDoubleArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSSArchives_sos_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecIntegerArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TSSArchives_sos_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecStringArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TSSArchives_sos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TSSArchives_sos_proto_goTypes,
		DependencyIndexes: file_TSSArchives_sos_proto_depIdxs,
		MessageInfos:      file_TSSArchives_sos_proto_msgTypes,
	}.Build()
	File_TSSArchives_sos_proto = out.File
	file_TSSArchives_sos_proto_rawDesc = nil
	file_TSSArchives_sos_proto_goTypes = nil
	file_TSSArchives_sos_proto_depIdxs = nil
}
